name: Check compilation and tests

on:
  push:
    branches: [ dev_antoine ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Compil_on_Linx:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    name: Linux_compil
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip3 install conan --upgrade
          mkdir -p artifacts
          make fclean
          make > artifacts/complete_linux_build_log.txt
          tail artifacts/complete_linux_build_log.txt -n10 > artifacts/end_linux_build.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts/complete_linux_build_log.txt
            artifacts/end_linux_build.txt

  Compil_on_Windows:
    runs-on: windows-latest
    name: Windows_compil
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip3 install conan
          pip3 install conan --upgrade
          mkdir -p artifacts
          mkdir -p build
          (cd build && conan install .. --build=missing && cmake .. && cmake --build .) > artifacts\complete_Windows_build_log.txt
          tail artifacts\complete_Windows_build_log.txt -n 10 > artifacts\end_Windows_build.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts\complete_Windows_build_log.txt
            artifacts\end_Windows_build.txt

#  Tests:
#    runs-on: ubuntu-latest
#    container: epitechcontent/epitest-docker:devel
#    name: tests
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          mkdir -p artifacts
#          make fclean
#          make tests_run
#          ./unit_tests &> artifacts/tests_results.txt
#          gcovr -e tests/ &> artifacts/coverage_lines.txt
#          gcovr -e tests/ -b &> artifacts/coverage_branches.txt
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Tests results
#          path: |
#            artifacts/tests_results.txt
#            artifacts/coverage_lines.txt
#            artifacts/coverage_branches.txt
