name: Compilation

on:
  push:
    commit-ignore:
      - [skip ci]
      - [skip compilation]
  workflow_dispatch:

jobs:
  Compile_on_Linx:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequires
        run: ./requires
        working-directory: ./.github/workflows/
      - name: Install, update and configure conan
        run: |
          pip3 install conan
          pip3 install conan --upgrade
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Create artifacts folder
        run: mkdir -p artifacts
        working-directory: ./
      - name: Recompile project
        run: |
          make re
          make fclean
        working-directory: ./
      - name: Compile project
        run: make > artifacts/complete_linux_build_log.txt
        working-directory: ./
      - name: Get end of compilation
        run: tail artifacts/complete_linux_build_log.txt -n10 > artifacts/end_linux_build.txt
        working-directory: ./
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts/complete_linux_build_log.txt
            artifacts/end_linux_build.txt

  Compil_on_Windows:
    runs-on: windows-latest
    name: Windows
    steps:
      - uses: actions/checkout@v2
      - name: Install and update conan
        run: |
          pip3 install conan
          pip3 install conan --upgrade
      - name: Create artifacts folder
        run: mkdir -p artifacts
        working-directory: ./
      - name: Recompile project
        run: |
          rm -rf build
          mkdir -p build && cd build && conan install .. --build=missing && cmake .. && cmake --build .
          rm -rf build
      - name: Compile project
        run: (mkdir -p build && cd build && conan install .. --build=missing && cmake .. && cmake --build .) > artifacts\complete_Windows_build_log.txt
      - name: Get end of compilation
        run: tail artifacts\complete_Windows_build_log.txt -n 10 > artifacts\end_Windows_build.txt
        working-directory: ./
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts\complete_Windows_build_log.txt
            artifacts\end_Windows_build.txt
