name: Compilation

on:
  push:
    branches:
      - master
      - dev_antoine
    commit-ignore:
      - [ skip ci ]
  workflow_dispatch:

jobs:
  Compile_on_Linx:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequires
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libudev-dev \
          pkg-config \
          libgl-dev \
          xorg-dev \
          libx11-xcb-dev  \
          libxcb-render0-dev \
          libxcb-render-util0-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxcb-xinerama0-dev \
          xkb-data \
          libxcb-dri3-dev \
          libxcb-util-dev
      - name: Install and update conan
        run: |
          pip3 install conan
          pip3 install conan --upgrade
      - name: Create artifacts folder
        run: mkdir -p artifacts
        working-directory: ./
      - name: Compile project
        run: make > artifacts/complete_linux_build_log.txt
        working-directory: ./
      - name: Get end of compilation
        run: tail artifacts/complete_linux_build_log.txt -n10 > artifacts/end_linux_build.txt
        working-directory: ./
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts/complete_linux_build_log.txt
            artifacts/end_linux_build.txt

  Compil_on_Windows:
    runs-on: windows-latest
    name: Windows
    steps:
      - uses: actions/checkout@v2
      - name: Install and update conan
        run: |
          pip3 install conan
          pip3 install conan --upgrade
      - name: Create artifacts folder
        run: mkdir -p artifacts
        working-directory: ./
      - name: Compile project
        run: (mkdir -p build && cd build && conan install .. --build=missing && cmake .. && cmake --build .) > artifacts\complete_Windows_build_log.txt
      - name: Get end of compilation
        run: tail artifacts\complete_Windows_build_log.txt -n 10 > artifacts\end_Windows_build.txt
        working-directory: ./
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts\complete_Windows_build_log.txt
            artifacts\end_Windows_build.txt

#  Tests:
#    runs-on: ubuntu-latest
#    container: epitechcontent/epitest-docker:devel
#    name: tests
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          mkdir -p artifacts
#          make fclean
#          make tests_run
#          ./unit_tests &> artifacts/tests_results.txt
#          gcovr -e tests/ &> artifacts/coverage_lines.txt
#          gcovr -e tests/ -b &> artifacts/coverage_branches.txt
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Tests results
#          path: |
#            artifacts/tests_results.txt
#            artifacts/coverage_lines.txt
#            artifacts/coverage_branches.txt
