name: Windows Compilation

on:
  push:
    branches:
      - master
    commit-ignore:
      - [skip ci]
      - [skip windows]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Compil_on_Windows:
    runs-on: windows-latest
    name: Windows_compil
    steps:
      - uses: actions/checkout@v2
      - name: Install and update conan
        run: |
          pip3 install conan
          pip3 install conan --upgrade
      - name: Create artifacts folder
        run: mkdir -p artifacts
        working-directory: ./
      - name: Compile project
        run: (mkdir -p build && cd build && conan install .. --build=missing && cmake .. && cmake --build .) > artifacts\complete_Windows_build_log.txt
      - name: Get end of compilation
        run: tail artifacts\complete_Windows_build_log.txt -n 10 > artifacts\end_Windows_build.txt
        working-directory: ./
      - uses: actions/upload-artifact@v2
        with:
          name: Build log
          path: |
            artifacts\complete_Windows_build_log.txt
            artifacts\end_Windows_build.txt